/**
 * This file include all the declear of ncs windows
 *
 * Please don't modify it
 *
 * This file is auto generated by hybridStudio
 *
 * ANY WORD WRITTEN BY USER WOULD BE DELETE BY MSTUDIO !
 *
 */

#ifndef NCS_MAINWNDS_H
#define NCS_MAINWNDS_H

#ifdef __cpluspus
extern "C" {
#endif

/**
 * please predefine marco NCS_WND_EXPORT
 * if you want export these ncs main window function
 * to other libraries
 */
#ifndef NCS_WND_EXPORT
#define NCS_WND_EXPORT
#endif


#ifdef __cplusplus
}
#endif

#endif /* end of window list */

